FA.JustBlog.Core/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service.ModelRepository;
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace FA.JustBlog.Core.Controllers
{
    [AllowAnonymous]
    public class PostController : Controller
    {

        private readonly IUnitOfWork unitOfWork;
        private readonly ILogger _logger;
        private readonly BlogContext _ctx;
        private readonly UserManager<User> _userManager;
        public PostController(IUnitOfWork unitOfWork, ILogger<PostController> logger,BlogContext blogContext, UserManager<User> userManager)
        {
            this.unitOfWork = unitOfWork;
            _logger = logger;
            _ctx = blogContext;
            _userManager = userManager;
        }
        public IActionResult PostDetail(int year, int month, string title)
        {
            var post = unitOfWork.postRepository.FindPost(year, month, title);
            return View(post);
        }
        public IActionResult Search(string search)
        {
            var list = from x in _ctx.Posts select x;
            var user = _userManager.GetUserAsync(User).GetAwaiter().GetResult();
            if(user == null)
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search));
                return View(list.ToList());

            }
            var userRole = _userManager.GetRolesAsync(user).Result;
            if(userRole.Contains("Admin") || userRole.Contains("BlogOwner"))
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search) || x.Content.Contains(search));

            }
            else
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search));

            }
            return View(list.ToList());
        }
        public IActionResult MostViewedPosts()
        {
            _logger.LogInformation("Get most view post");
            List<Post> list = unitOfWork.postRepository.Find(x=>x.IsPublished).OrderByDescending(x => x.View).Take(5).ToList();
            return PartialView("_ListPost", list);
        }
        public IActionResult LatestPosts()
        {
            List<Post> list = unitOfWork.postRepository.Find(x => x.IsPublished).OrderByDescending(x => x.CreatedDate).Take(5).ToList();
            return PartialView("_ListPost", list);
        }
    }
}

FA.JustBlog.Core/ViewComponents/CategoryViewComponent.cs
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Core.ViewComponents
{
    public class CategoryViewComponent : ViewComponent
    {
        private readonly IUnitOfWork unitOfWork;
        public CategoryViewComponent(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IViewComponentResult Invoke()
        {
            return View(unitOfWork.categoryRepository.GetAll());
        }
    }
}

FA.JustBlog.Core/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#!">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
            </div>
        </div>
    </div>
</footer>

FA.JustBlog.Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FA.JustBlog.Core.styles.css" asp-append-version="true" />
    
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/">Just Blog</a>
            <form method="post" asp-action="Search" asp-controller="Post">
                <input class="form-control" type="text" name="Search" placeholder="Search" />
            </form>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-controller="Home" asp-action="Index">Home</a>

                    </li>
                    @await Component.InvokeAsync("Category")
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>@ViewData["Title"]</h1>
                        <span class="subheading">@Html.Raw(ViewData["CreatedDate"])</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
  
    <div class="container">

        <div>
            @RenderBody()
            
        </div>
    </div>
    <partial name="_Footer" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
      
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>