FA.JustBlog.Core/Models/Post.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FA.JustBlog.Core.Models
{
    public class Post
    {
        public int Id { get; set; }
        public string Title {  get; set; }
        public string? ShortDescription { get; set; } 
        public string Content {  get; set; }
        public int View { get; set; }
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public virtual Category? Category { get; set; }
        public virtual List<PostTag>? PostTags { get; set; }
        [DisplayName("Created Date")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;
        public virtual List<PostRate>? PostRate { get; set; }
        public virtual List<Comment>? Comment { get; set; }
        public bool IsPublished { get; set; } = false;
    }
}

FA.JustBlog.Core/Areas/Admin/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.PaginateList;
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FA.JustBlog.Core.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,BlogOwner,Contributor,User")]
    public class PostController : Controller
    {
        private readonly BlogContext _context;
        private readonly IUnitOfWork _unitOfWork;

        public PostController(BlogContext context, IUnitOfWork unitOfWork)
        {
            _context = context;
            _unitOfWork = unitOfWork;
        }

        [Authorize(Roles = "Admin,BlogOwner,Contributor,User")]
        // GET: Admin/Post
        public async Task<IActionResult> Index(string sortBy,string filtering,int page = 1,int pageSize = 10)
        {

            if(page < 1)
            {
                page = 1;
            }
            var blogContext = from p in _context.Posts
                              select p;
            if(blogContext == null)
            {
                return View(null);
            }
            if (!string.IsNullOrWhiteSpace(filtering))
            {
                if(filtering.ToLower() == "published")
                {
                    ViewData["filtering"] = filtering;
                    blogContext = blogContext.Where(x => x.IsPublished);
                }else if(filtering.ToLower() == "unpublished")
                {
                    ViewData["filtering"] = filtering;
                    blogContext = blogContext.Where(x => !x.IsPublished);

                }
            }
            if(!string.IsNullOrWhiteSpace(sortBy))
            {
                if (sortBy.ToLower() == "viewed")
                {
                    ViewBag.SortBy = sortBy;
                    blogContext = blogContext.OrderByDescending(x => x.View);
                } else if (sortBy.ToLower() == "recent")
                {
                    ViewBag.SortBy = sortBy;
                    blogContext = blogContext.OrderByDescending(x => x.CreatedDate);
                } else if (sortBy.ToLower() == "interesting")
                {
                    ViewBag.SortBy = sortBy;
                    
                    blogContext = from p in _context.Posts.DefaultIfEmpty()
                                  join x in
                                      (from pr in _context.PostRate
                                       group pr by pr.PostId into g
                                       select new
                                       {
                                           PostId = g.Key,
                                           AVGRate = g.Average(pr => pr.Rate)
                                       })
                                  on p.Id equals x.PostId into postrate
                                  from pr in postrate.DefaultIfEmpty()
                                  orderby pr.AVGRate descending
                                  select p;

                }
                   
            }
            ViewBag.PageSize = pageSize;

            return View(await PaginatedList<Post>.CreateAsync(blogContext, page, pageSize));
        }

        // GET: Admin/Post/Details/5
        [Authorize(Roles ="Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Admin/Post/Create
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public IActionResult Create()
        {
            var listCate = _context.Categories.ToList();
            ViewBag.Categories = listCate;
            var listTag = _context.Tags.ToList();
            ViewBag.Tags = listTag;
            return View();
        }

        // POST: Admin/Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> Create([Bind("Id,Title,Content,View,CategoryId,CreatedDate,IsPublished")] Post post,List<int> PostTags)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.postRepository.Add(post);
                foreach(var tagid in PostTags)
                {
                    _context.PostTag.Add(new PostTag { PostId = post.Id, TagId = tagid });
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            var listTag = _context.Tags.ToList();
            ViewBag.Tags = listTag;
            var listCate = _context.Categories.ToList();
            ViewBag.Categories = listCate;
            return View(post);
        }

        // GET: Admin/Post/Edit/5
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.Include(p=>p.PostTags).FirstOrDefaultAsync(x=>x.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Name", post);

            var listTag = from T in _context.Tags
                          join pt in _context.PostTag.Where(x=>x.PostId == id)
                             on T.Id equals pt.TagId into gj
                           from x in gj.DefaultIfEmpty()
                          select new
                          {
                              TagName = T.Name,
                              TagId = T.Id,
                              IsSelected = x.TagId !=null
                          };

            //ViewBag.Tag = new MultiSelectList(_context.Tags, "Id", "Name", post.PostTags.Select(pt => pt.TagId).ToList());

            ViewBag.ListTag = listTag.ToList();
            return View(post);
        }

        // POST: Admin/Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Content,View,CategoryId,IsPublished")] Post post,List<int> PostTags)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                try
                {
                    _context.Update(post);
                    var listOldPostTag = _context.PostTag.Where(x=>x.PostId == post.Id).ToList();
                    _context.PostTag.RemoveRange(listOldPostTag);

                    List<PostTag> listNewPostTag = new List<PostTag>();
                    foreach(var item in PostTags)
                    {
                        listNewPostTag.Add(new PostTag { PostId = post.Id, TagId = item });
                    }
                    await _context.PostTag.AddRangeAsync(listNewPostTag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Id", post.CategoryId);
            return View(post);
        }

        // GET: Admin/Post/Delete/5
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // POST: Admin/Post/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,BlogOwner,Contributor")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'BlogContext.Posts'  is null.");
            }
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
                
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
          return (_context.Posts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

FA.JustBlog.Core/Controllers/CategoryController.cs
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Core.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult PostByCategory(string name)
        {
            var Post = unitOfWork.categoryRepository.PostByCategory(name);
            return View("~/Views/Post/_ListPost.cshtml",Post);
        }
    }
}

FA.JustBlog.Core/Controllers/PostController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service.ModelRepository;
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace FA.JustBlog.Core.Controllers
{
    [AllowAnonymous]
    public class PostController : Controller
    {

        private readonly IUnitOfWork unitOfWork;
        private readonly ILogger _logger;
        private readonly BlogContext _ctx;
        private readonly UserManager<User> _userManager;
        public PostController(IUnitOfWork unitOfWork, ILogger<PostController> logger,BlogContext blogContext, UserManager<User> userManager)
        {
            this.unitOfWork = unitOfWork;
            _logger = logger;
            _ctx = blogContext;
            _userManager = userManager;
        }
        public IActionResult PostDetail(int year, int month, string title)
        {
            var post = unitOfWork.postRepository.FindPost(year, month, title);
            return View(post);
        }
        public IActionResult Search(string search)
        {
            var list = from x in _ctx.Posts select x;
            var user = _userManager.GetUserAsync(User).GetAwaiter().GetResult();
            if(user == null)
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search));
                return View(list.ToList());

            }
            var userRole = _userManager.GetRolesAsync(user).Result;
            if(userRole.Contains("Admin") || userRole.Contains("BlogOwner"))
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search) || x.Content.Contains(search));

            }
            else
            {
                list = list.Where(x => x.Title.Contains(search) || x.ShortDescription.Contains(search));

            }
            return View(list.ToList());
        }
        public IActionResult MostViewedPosts()
        {
            _logger.LogInformation("Get most view post");
            List<Post> list = unitOfWork.postRepository.Find(x=>x.IsPublished).OrderByDescending(x => x.View).Take(5).ToList();
            return PartialView("_ListPost", list);
        }
        public IActionResult LatestPosts()
        {
            List<Post> list = unitOfWork.postRepository.Find(x => x.IsPublished).OrderByDescending(x => x.CreatedDate).Take(5).ToList();
            return PartialView("_ListPost", list);
        }
    }
}

FA.JustBlog.Core/Controllers/TagController.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service.ModelRepository;
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Core.Controllers
{
    [AllowAnonymous]

    public class TagController : Controller
    {   
        private readonly IUnitOfWork unitOfWork;
        public TagController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public IActionResult PopularTags()
        {
            IEnumerable<PostTagCountVM> tags = unitOfWork.tagRepository.getPopularTag();

            return PartialView("_PopularTags", tags);
        }
        public IActionResult PostByTag(string name)
        {
            var listPost = unitOfWork.tagRepository.GetPostByTagName(name);
            return View("~/Views/Post/_ListPost.cshtml", listPost);
        }
    }
}

FA.JustBlog.Core/ViewComponents/CommentViewComponent.cs
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service.UnitOfWork;
using Microsoft.AspNetCore.Mvc;

namespace FA.JustBlog.Core.ViewComponents
{
    public class CommentViewComponent : ViewComponent
    {
        private readonly IUnitOfWork unitOfWork;
        public CommentViewComponent(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public  IViewComponentResult Invoke(List<Comment> Comments,int PostId)
        {
            var item = new
            {
                comment = Comments,
                PostId = PostId
            };
            return View(item);
        }
    }
}

FA.JustBlog.Core/Views/Post/PostDetail.cshtml
@using Microsoft.AspNetCore.Identity
@model Post
@inject UserManager<User> _userManager
@{
    ViewData["Title"] = Model.Title;
    ViewData["CreatedDate"] = "<span class='meta'>Posted " + @Model.CreatedDate + " by " + @Model.View + " view(s)</span>";
    var user = await _userManager.GetUserAsync(User);
}
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <p>@Html.Raw(Model.Content)</p>
            </div>
        </div>
    </div>
</article>
@if (user != null)
{
    <form id="PostComment" method="post" class="mb-5">
        <input id="PostId" name="PostId" value="@Model.Id" hidden />
        <input id="UserId" name="UserId" value="@user.Id" hidden />
        <div class="form-group">
            <label for="comment">Your Comment</label>
            <textarea id="Content" name="Content" class="form-control" rows="3"></textarea>
            <span></span>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <div class="form-group">
                <div class="g-recaptcha" data-callback="recaptchaCallback" data-sitekey="6LcCdy4pAAAAAH0mWzIRLGnv-CEaenXVF-2--Wqw"></div>
            </div>
            <div ><button id="submitComment" type="submit" class="btn btn-primary">Send</button></div>
        </div>
    </form>
}
else
{
    <p>You need to <a href="/login">login</a> to comment</p>
}

<div id="comment">

    @await Component.InvokeAsync("Comment", new { Comments = Model.Comment, PostId = Model.Id })
</div>

@section Scripts {
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
    <script>
        function recaptchaCallback() {
            $('#submitComment').removeAttr('disabled');
        };
        $("#PostComment").on("submit", async (e) => {
            e.preventDefault();
            // const UserId = $('#UserId').val()
            // const PostId = $('#PostId').val()
            // const Content = $('#Content').val()
            // const formData = {
            //     UserId,
            //     PostId,
            //     Content,
            // }
            // console.log(formData)

            // // var res = await fetch("/Comment/SaveComment", {method: "Post", formData: formData})
            // // .then(res=>res.text)
            // $('#comment').load('/Comment/SaveComment',formData)
        })

        $('#submitComment').on('click', () => {
            const UserId = $('#UserId').val()
            const PostId = $('#PostId').val()
            const Content = $('#Content').val()
            if (Content.trim().length == 0) {
                return alert("Please input comment")
            }
            if (grecaptcha.getResponse().length == 0) {
                return alert("Please check the captcha!")
            }
         
            const formData = {
                UserId,
                PostId,
                Content,
            }
            $.post('/Comment/SaveComment', formData, (data, status) => {
                console.log(status)
                $('#comment').html(`${data}`)
                $('#Content').val('')
                grecaptcha.reset()
            })
           
        })
    </script>
}

FA.JustBlog.Core/Views/Post/Search.cshtml
@model List<Post>

<h1>Search Post</h1>
<hr />
<div>
    <div class="d-flex">
        <div id="lastestPost">
            <partial name="_ListPost" model="Model" />
        </div>
       @*  <div>
            <partial name="~/Views/Home/_PartialAboutCard.cshtml" />
            <div id="popularTag">
            </div>
        </div> *@
    </div>

  @*   <div>
        <h1>Most Viewed Post</h1>
        <hr />
        <div id="MostViewedPosts">
        </div>
    </div> *@
</div>

@section Scripts {
    <script>
        $('#popularTag').load("/Tag/PopularTags")
    </script>
}

FA.JustBlog.Core/Views/Post/_ListPost.cshtml
@using FA.JustBlog.Core.Service.UnitOfWork
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Post>
@{
    string FormatDateTime(DateTime dt)
    {
        var timeDifference = DateTime.Now - dt;

        if (timeDifference.TotalMilliseconds < 60000) 
        {
            int secondsAgo = (int)timeDifference.TotalSeconds;
            return $"Posted on {secondsAgo} second{(secondsAgo != 1 ? "s" : "")} ago";
        }
        else if (timeDifference.TotalMilliseconds < 3600000)
        {
            int minutesAgo = (int)timeDifference.TotalMinutes;
            return $"Posted on {minutesAgo} minute{(minutesAgo != 1 ? "s" : "")} ago";
        }
        else if (timeDifference.TotalMilliseconds < 86400000) 
        {
            int hoursAgo = (int)timeDifference.TotalHours;
            return $"Posted on {hoursAgo} hour{(hoursAgo != 1 ? "s" : "")} ago";
        }
        else if (timeDifference.TotalMicroseconds < 172800000)
        {
            return $"Posted on Yesterday on {timeDifference.Hours}:{timeDifference.Minutes}";
        }
        else // More than 2 days
        {
            
            return $"Posted on {dt}";

        }
    }
}
<div class="d-flex">
    <div id="lastestPost">
        @{
            if (Model.Any())
            {
                @foreach (var item in Model)
                {

                    <!-- Post preview-->
                    <div class="post-preview">
                        <a href="/Post/@item.CreatedDate.Year/@item.CreatedDate.Month/@item.Title.Replace(" ","-")">
                            <h2 class="post-title">@item.Title</h2>

                        </a>
                        <p class="post-meta">
                            @FormatDateTime(item.CreatedDate) by @item.View view(s)
                        </p>
                        <p>
                            Category: <a class="text-decoration-underline" asp-action="@item.Category.Name.Replace(" ","-")" asp-controller="Category">
                                @item.Category.Name
                            </a>
                        </p>
                        <p>
                            Tag: @{
                                var tag = from x in item.PostTags
                                          select x;
                                foreach (var item2 in tag)
                                {
                                    <a asp-controller="Tag" asp-action="@item2.Tag.Name.Replace(" ","-")" class="border bg-black text-white p-1">@item2.Tag.Name</a>
                                }
                            }
                        </p>

                        <div class="post-subtitle">@Html.Raw(item.Content)</div>
                    </div>

                    <hr class="my-4">

                }
            }
            else
            {
                <p>No post in this tag</p>
            }

        }
    </div>

</div>
           

@section Scripts{
    <script>$('#popularTag').load("/Tag/PopularTags")</script>
}